### ISSUE TITLE
Assignment1 code review

### ISSUE THREAD

**Issue by blackboxlogic** [zaqmju1/Cos470#1]
Regarding:
https://github.com/zaqmju1/Cos470/blob/6d8b93aae6aaf68567a68a8e271a6f0ea9018356/Assignment1/DollarWords/DollarWords/Program.cs#L17
This might not hold true for other input files. I suggest initializing these variables with `null` to indicate no value yet, or initialize it with the first word from the input.

Regarding:
https://github.com/zaqmju1/Cos470/blob/6d8b93aae6aaf68567a68a8e271a6f0ea9018356/Assignment1/DollarWords/DollarWords/Program.cs#L47
Repeated string concatenation is a performance issue. Recommend using string builder.

**Comment by zaqmju1** [comment]
Changed shortestLen to initialize at 0; Placed a condition for the first instance of a dollar word to set the first shortest word.

Changed DollarWords from String to StringBuilder for better concatenation.
