### ISSUE TITLE
Assignment 3

### ISSUE THREAD

**Issue by blackboxlogic** [zaqmju1/Cos470#4]
You should be using .gitignore

Nice unit tests

Is this trying to strip milliseconds from the datetime?
https://github.com/zaqmju1/Cos470/blob/129714ffc16310e58dd3430c5f2a5ea213cf9286/Assignment3/A3ClassLibrary/A3ClassLibrary/JsonLoc.cs#L15

I think this is misses some edge cases (only catches when A is slightly ahead of B but not when B is slightly ahead of A). I suggest using subtraction and absolution value to determine time "distance".
https://github.com/zaqmju1/Cos470/blob/129714ffc16310e58dd3430c5f2a5ea213cf9286/Assignment3/A3ClassLibrary/A3ClassLibrary/JsonLoc.cs#L79

Oh! same for checking distance ranges. Subtraction is your friend.
https://github.com/zaqmju1/Cos470/blob/129714ffc16310e58dd3430c5f2a5ea213cf9286/Assignment3/A3ClassLibrary/A3ClassLibrary/JsonLoc.cs#L82

**Comment by zaqmju1** [comment]
Changed the classes to better suit the given data. I also changed the range checking to use subtraction with absolute values as you suggested.

**Comment by blackboxlogic** [comment]
### Data model
Yep
### Business logic
I like your use of upper and lower time bounds in `Alibi()`. No one else did that.
The way you implemented distance checking in `haveMet()` is a little odd. The units of `distGapThresh` are unclear and you check lat and lon separately. Probably good enough.
### Tests
Unit test: And they pass!
### Api
Controller:
That's nicely configurable!
```//public ActionResult<IEnumerable<string>> GetHaveMet()``` is commented out. -5 pts ?
Regarding: ```public ActionResult<IEnumerable<string>> GetAlibi()```
It looks like you tried to make the response "human readable" by returning strings. An API would usually just return the data model, and whoever asked for it would be responsible for formatting it. For you, you would just return `al`. No points deducted here.
### Organization
Needs gitIgnore folders: -3 points
* bin
* obj
* .vs
* .user
